included:
  - pokemonCardApp/
excluded:
  - Pods/
disabled_rules:
  - trailing_whitespace # 余分に改行がある方が視認性が上がる為

# 一行の文字列制限を100文字から300文字に変更
line_length: 300
# メソッドの行数制限
function_body_length:
  - 100 # warning
  - 200 # error
# 1ファイルの行数制限
file_length:
  - 500 # warning
  - 1000 # error
# 型の行数制限
type_body_length:
  - 400 # warning
  - 600 # error
identifier_name:
  excluded:
  - i
  - id
  - db
